SELECT * FROM excel.`just data`;
use excel;
select* from `just data`;
-- to count total number of rows--
select count(*) from `just data`;
-- select distinct/unique data
select distinct * from `just data`;
select count(*) from (select distinct * from `just data`) as assassin;
-- calculate the total revenue generated in the bike sales--
select sum(revenue) as total_revenue from `just data`;
select sum(order_quantity*unit_price) from`just data`;

-- calculate the average selling price of bike--
select avg(unit_price) as average_price from `just data`;

/* calculate the total revenue generated by each countries and highlight top 5 countries
with high and low revenue*/
select * from `just data`;
-- top 5 countries with high revenue
select country,sum(revenue) as total_revenue from `just data` group by country order by total_revenue
 desc limit 3;
 -- top 5 countries with low revenue
 select country,sum(revenue) as total_revenue from `just data` group by country order by total_revenue
 asc limit 3;
 -- states in usa with the highest revenue
 select country,state,sum(revenue) as total_revenue from `just data` where country="united states" group by country,state
  order by total_revenue desc limit 5;
  
   select country,state,sum(revenue) as total_revenue from `just data` group by country,state
   having country="united states" order by total_revenue desc limit 5;
   
   select country,state,sum(revenue) as total_revenue from `just data` where country="united states" group by country,state
  having state="washington" order by total_revenue desc limit 5;
   
  -- calculate sales based on age group
  select age_group,sum(revenue) as total_revenue from `just data` group by age_group 
  order by total_revenue desc limit 4;
 use excel;
 
-- revenue generated in terms of gender
select* from `just data`;
 select customer_gender,sum(revenue) as total_revenue from `just data` group by customer_gender 
 order by total_revenue desc;
  -- revenue by gender in top countries
  
  select customer_gender,country,sum(revenue) as total_revenue from `just data` group by 
  customer_gender,country order by total_revenue desc limit 5;
  
  -- Products that are more profitable
  select product_category,sum(revenue) as total_revenue from `just data` group by 
product_category order by total_revenue desc;
select product,product_category,sum(revenue) as total_revenue from `just data` 
where product_category="bikes" group by product,product_category order by total_revenue desc;

select product_category,sum(revenue) as total_revenue from `just data` 
where product_category="bikes" group by product_category order by total_revenue;
  
select product,sum(revenue) as total_revenue from `just data` group by product order by total_revenue desc limit 7;
-- check revenue made over the years
select `year`,sum(revenue) as total_revenue from `just data` group by `year` order by total_revenue desc;
  use excel;
  select* from `just data`;
select `year`,`month`,sum(revenue) as total_revenue from `just data` where `month` in("january","february","march") 
group by `month`,`year` having year="2015" order by total_revenue desc;
select `year`,`month`,sum(revenue) as total_revenue from `just data` where `month` in("january","february","march") 
group by `month`,`year` having year="2016" order by total_revenue desc;
select `year`,`month`,sum(revenue) as total_revenue from `just data` where `month` in("january","february","march") 
group by `month`,`year` having year="2013" order by total_revenue desc;